# Generated by Django 3.0.7 on 2020-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='particular',
            field=models.TextField(blank=True),
        ),
    ]
