# Generated by Django 3.0.7 on 2020-06-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_transaction_particular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cash_in',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cash_out',
            field=models.FloatField(default=0),
        ),
    ]
